title: "Cache Cleaner - Clean & Fast Browsing"
description: "Keep your browser fast and clean with Cache Cleaner extension"
baseurl: ""
url: "https://sergeycommit.github.io/cache_cleaner"

# Jekyll settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
author: sergeycommit
lang: en-US

# Social settings
github:
  repository_url: https://github.com/sergeycommit/cache_cleaner

# Exclude files from processing (but keep images accessible)
exclude:
  - src/popup.js
  - src/popup.css
  - src/popup.html
  - src/service-worker.js
  - src/manifest.json
  - src/_locales/
  - src/package.json
  - src/README.md
  - Archive.zip
  - README.md